FROM wordpress:6.8.3-php8.3

# Install composer
RUN php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" \
    && php composer-setup.php --install-dir=/usr/local/bin --filename=composer \
    && php -r "unlink('composer-setup.php');"

ENV SHELL=/bin/bash
ENV PATH=/var/www/html/wp-content/plugins/ca-manager/vendor/bin:${PATH}
